import {before,after,test} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
let server;const origin='http://127.0.0.1:4319';
before(async()=>{server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'4319'},stdio:'pipe'});await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Server did not start')),10000);server.stdout.on('data',data=>{out+=data;if(out.includes('http://localhost:')){clearTimeout(timer);resolve();}});server.on('exit',code=>{clearTimeout(timer);reject(Error('Server exited '+code));});});});
after(()=>{server?.kill('SIGTERM');});
test('HTML and all entry assets serve with appropriate content types',async()=>{for(const [path,type] of [['/','text/html'],['/styles.css','text/css'],['/src/app.js','text/javascript'],['/assets/favicon.svg','image/svg+xml']]){const res=await fetch(origin+path);assert.equal(res.status,200);assert.ok(res.headers.get('content-type').includes(type));}});
test('response security policy prohibits inline scripts, remote connections and framing',async()=>{const r=await fetch(origin);const csp=r.headers.get('content-security-policy');assert.ok(csp.includes("script-src 'self'"));assert.ok(csp.includes("frame-ancestors 'none'"));assert.ok(!csp.includes('unsafe-inline'));assert.equal(r.headers.get('x-content-type-options'),'nosniff');});
test('server does not expose package files, tests or traversal paths',async()=>{for(const path of ['/package.json','/.env','/tests/domain.test.mjs','/src/%2e%2e%2fpackage.json','/src/%2e%2e%2f%2e%2e%2fupload/OntoTrail-Demo-2.html']){const r=await fetch(origin+path);assert.ok([403,404].includes(r.status),`${path}: ${r.status}`);}});
test('unsupported HTTP methods fail closed',async()=>{const r=await fetch(origin,{method:'POST',body:'test'});assert.equal(r.status,405);});
test('HEAD response has headers but no response body',async()=>{const r=await fetch(origin,{method:'HEAD'});assert.equal(r.status,200);assert.equal(await r.text(),'');});
