const brand='<a class="entry-brand" href="#home"><img src="/assets/ontotrail-mark.png" alt=""><span class="entry-brand-name">OntoTrail</span></a>';
let session=null;
async function auth(method='GET',body){
  const response=await fetch('/api/auth',{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});
  const data=await response.json().catch(()=>({}));
  if(!response.ok)throw Error(data.error||'Authentication failed.');
  return data;
}
async function userApi(method='GET',body){
  const response=await fetch('/api/tenant-users',{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});
  const data=await response.json().catch(()=>({}));
  if(!response.ok)throw Error(data.error||'User management failed.');
  return data;
}
function roleLabel(role){return role==='platform_admin'?'OntoTrail Platform Admin':role==='client_admin'?'Client Admin':'Client User';}
function applySession(value){
  session=value||null;window.__ONTOTRAIL_SESSION=session;
  const ws=document.querySelector('.sidebar-bottom strong');const sub=document.querySelector('.sidebar-bottom span');const avatar=document.querySelector('.workspace-avatar');const users=document.querySelector('[data-client-users]');const role=document.querySelector('[data-role-badge]');
  let displayName=session?.name||'';try{displayName=localStorage.getItem('ontotrail_profile_name')||displayName;}catch{}
  if(ws)ws.textContent=displayName||'Protected workspace';if(sub)sub.textContent=session?`${roleLabel(session.role)} · ${session.tenant||''}`:'Client workspace';if(avatar){const initials=(displayName||'User').split(/\s+/).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase();avatar.textContent=initials||'U';}if(users)users.hidden=session?.role!=='client_admin';if(role)role.textContent=session?roleLabel(session.role):'';
  window.dispatchEvent(new CustomEvent('ontotrail-session',{detail:session}));
}
export function homePage(){return `<header class="entry-nav">${brand}<nav aria-label="Home navigation"><a href="#features">Platform</a><a href="#login">Sign in</a><a class="primary" href="#login">Open workspace →</a></nav></header><main class="landing" id="entry-main" tabindex="-1"><section class="hero"><div class="hero-copy"><p class="entry-kicker">CONNECTED SUPPLY CHAIN INTELLIGENCE</p><h1>Every exposure.<br>Every dependency.<br><em>A clearer decision.</em></h1><p class="hero-description">OntoTrail connects India import exposure, commodity concentration, transport dependency and weather intelligence in one governed decision workspace.</p><div class="hero-actions"><a class="primary" href="#login">Sign in →</a><a class="secondary" href="#features">Explore the platform</a></div></div><div class="hero-visual product-preview" aria-label="OntoTrail platform illustration"><div class="visual-top"><span class="mini-brand">◉ OntoTrail</span><span class="mini-pill">CONNECTED INTELLIGENCE</span></div><div class="product-orbit"><div class="orbit-node">Countries</div><div class="orbit-node">Commodities</div><div class="orbit-center">Semantic layer</div><div class="orbit-node">Transport</div><div class="orbit-node">Weather</div></div><div class="product-strip"><span>Trace exposure</span><span>Stress-test risk</span><span>Ask in natural language</span></div></div></section><section class="landing-features" id="features"><div class="section-intro"><p class="entry-kicker">FROM SIGNAL TO ACTION</p><h2>Less searching.<br>More understanding.</h2><p>A connected workspace for supply-chain planning, impact analysis and conversational analytics.</p></div><article><span class="feature-number">01 / VISIBILITY</span><h3>Know what is at risk.</h3><p>Connect origin countries, commodities, transport modes and weather signals in one governed risk view.</p></article><article><span class="feature-number">02 / TRACEABILITY</span><h3>Understand why.</h3><p>Trace analytical answers back to governed data and generated SQL.</p></article><article><span class="feature-number">03 / SCENARIOS</span><h3>Compare before you act.</h3><p>Apply transparent stress assumptions before making a mitigation decision.</p></article></section><section class="landing-cta"><div><p class="entry-kicker">ONTO TRAIL WORKSPACE</p><h2>Governed trade-risk decisions start here.</h2></div><a class="primary" href="#login">Sign in to OntoTrail →</a></section></main><footer class="entry-footer"><span>© ${new Date().getFullYear()} OntoTrail</span><span>Trade-risk ontology + conversational analytics</span><a href="#login">Sign in →</a></footer>`;}
export function authPage(){return `<div class="auth-layout"><aside class="auth-story">${brand}<div class="auth-story-copy"><p class="entry-kicker">ONTO TRAIL ACCESS</p><h1>One platform.<br>Different roles.<br><em>Scoped access.</em></h1><p>Sign in with the account provided to you. OntoTrail administrators, client administrators and client users each receive a role-specific experience.</p><div class="auth-proof"><span>01</span><div><strong>Platform administration</strong><small>Manage client organizations and account-level access.</small></div></div><div class="auth-proof"><span>02</span><div><strong>Client administration</strong><small>Manage users inside a single client workspace.</small></div></div><div class="auth-proof"><span>03</span><div><strong>Client analytics</strong><small>Work only with the authenticated tenant's supply-chain data.</small></div></div></div><small class="auth-story-footer">Authorized access only</small></aside><main class="auth-main" id="entry-main" tabindex="-1"><a class="back-home" href="#home">← Back to home</a><div class="auth-card"><span class="auth-tag">SIGN IN</span><h1>Welcome to OntoTrail.</h1><p class="auth-subtitle">Enter your work credentials to continue.</p><form id="entry-auth" autocomplete="off"><label class="auth-field">Work email<input name="email" type="email" required maxlength="254" autocomplete="username"></label><label class="auth-field" for="entry-password">Password</label><div class="password-wrap"><input id="entry-password" name="password" type="password" required maxlength="128" autocomplete="current-password"><button type="button" data-entry="password" aria-label="Show password">Show</button></div><p id="auth-message" role="status" aria-live="polite"></p><button class="primary auth-submit">Continue →</button></form></div><p class="auth-bottom">Connect the dots. Trace the answers.</p></main></div>`;}
function platformPage(){return `<div class="platform-admin" id="entry-main" tabindex="-1"><header class="platform-top"><div>${brand}<span class="platform-role">Platform administration</span></div><div><span>${session?.name||'OntoTrail Administrator'}</span><button class="text-button" data-auth-logout>Log out</button></div></header><main class="platform-main"><div class="platform-heading"><div><p class="entry-kicker">ONTO TRAIL ADMINISTRATION</p><h1>Client portfolio</h1><p>Manage organizations, access and integration health without exposing client operational data.</p></div><button class="primary">+ Add client</button></div><section class="platform-metrics"><article><span>Total clients</span><strong>1</strong><small>1 active</small></article><article><span>Total client users</span><strong>2</strong><small>1 admin · 1 user</small></article><article><span>Connected semantic views</span><strong>1</strong><small>Snowflake Cortex</small></article><article><span>Environment</span><strong>Healthy</strong><small>Production demo</small></article></section><section class="platform-panel"><div class="panel-heading"><div><h2>Clients</h2><p>Organizations provisioned on OntoTrail.</p></div><span class="subtle-label">1 organization</span></div><div class="table-scroll"><table><thead><tr><th>Client</th><th>Users</th><th>Client admins</th><th>Semantic model</th><th>Status</th><th></th></tr></thead><tbody><tr><td><strong>Nova Mobility India</strong><span class="cell-sub">Global import risk workspace</span></td><td>2</td><td>1</td><td>ONTOTRAIL_TRADE_RISK_ANALYST</td><td><span class="status covered">Active</span></td><td><button class="secondary small" data-platform-client>View account</button></td></tr></tbody></table></div></section><section class="platform-panel platform-split"><article><h2>Account controls</h2><p>Platform administrators can provision client organizations, assign client administrators and review integration status.</p></article><article><h2>Data boundary</h2><p>Operational supply-chain records remain inside each client workspace. This dashboard shows account metadata only.</p></article></section></main></div>`;}
function userManagerShell(){let dlg=document.querySelector('#user-manager-dialog');if(!dlg){dlg=document.createElement('dialog');dlg.id='user-manager-dialog';dlg.className='detail-dialog user-manager-dialog';document.body.append(dlg);}return dlg;}
function userRows(users){return users.map(u=>`<tr><td><strong>${escapeHtml(u.name)}</strong><span class="cell-sub">${escapeHtml(u.email)}</span></td><td>${escapeHtml(u.role)}</td><td><span class="status ${u.status==='Active'?'covered':'risk'}">${escapeHtml(u.status)}</span></td><td>${u.id==='coco-admin'?'Primary client admin':'Workspace access'}</td><td>${u.id==='coco-admin'?'—':u.status==='Active'?`<button class="text-button" data-user-action="deactivate" data-user-id="${escapeHtml(u.id)}">Deactivate</button>`:u.status==='Inactive'?`<button class="text-button" data-user-action="activate" data-user-id="${escapeHtml(u.id)}">Reactivate</button>`:`<button class="text-button" data-user-action="remove" data-user-id="${escapeHtml(u.id)}">Remove invite</button>`}</td></tr>`).join('');}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function showUsers(){const dlg=userManagerShell();dlg.innerHTML='<div class="detail-body"><p>Loading users…</p></div>';dlg.showModal();try{const data=await userApi();dlg.innerHTML=`<div class="dialog-head"><div><span class="eyebrow">NOVA MOBILITY INDIA</span><h2>Workspace users</h2><p>Client administrators manage access only inside their organization.</p></div><button class="icon-button" data-user-close aria-label="Close">×</button></div><div class="detail-body"><div class="tenant-user-stats"><span><strong>${data.users.length}</strong> users</span><span><strong>${data.users.filter(u=>u.role==='Client Admin').length}</strong> client admin</span><span><strong>${data.users.filter(u=>u.status==='Active').length}</strong> active</span></div><div class="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Scope</th><th></th></tr></thead><tbody>${userRows(data.users)}</tbody></table></div><form id="invite-user-form" class="invite-user-form"><div><label class="field-label">Name<input class="text-input" name="name" required maxlength="80" placeholder="Team member"></label></div><div><label class="field-label">Work email<input class="text-input" name="email" type="email" required maxlength="254" placeholder="name@company.com"></label></div><button class="primary">Invite user</button></form><p class="helper">Demo invitations appear in this authenticated workspace directory. Production identity provisioning would connect to the organization's identity provider.</p></div>`;}catch(err){dlg.innerHTML=`<div class="dialog-head"><h2>User management</h2><button class="icon-button" data-user-close>×</button></div><div class="detail-body"><p>${escapeHtml(err.message)}</p></div>`;}}
async function updateUser(action,id){await userApi('POST',{action,id});await showUsers();}
export function initWelcome(){
  const host=document.createElement('div');host.id='entry-root';document.body.append(host);const shell=document.querySelector('#shell');let ready=false;
  async function refreshSession(){try{const data=await auth();applySession(data.session);}catch{applySession(null);}ready=true;route();}
  function route(){if(!ready)return;let page=location.hash.slice(1)||'home';const publicPage=['home','login','features'].includes(page);if(session?.role==='platform_admin'&&!publicPage){host.hidden=false;shell.hidden=true;host.innerHTML=platformPage();document.title='OntoTrail · Platform administration';return;}if(!publicPage&&!session){history.replaceState(null,'',`${location.pathname}${location.search}#login`);page='login';}
    const active=publicPage||!session;host.hidden=!active;shell.hidden=active;document.querySelector('.skip-link').href=active?'#entry-main':'#main';
    if(!active){applySession(session);return;}host.innerHTML=page==='login'?authPage():homePage();document.title=`OntoTrail · ${page==='login'?'Sign in':'Connected supply chain intelligence'}`;if(page==='features')host.querySelector('#features')?.scrollIntoView();else window.scrollTo(0,0);
  }
  host.addEventListener('click',event=>{const button=event.target.closest('[data-entry]');if(button?.dataset.entry==='password'){const input=host.querySelector('#entry-password');const show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'Hide':'Show';}});
  host.addEventListener('submit',async event=>{if(event.target.id!=='entry-auth')return;event.preventDefault();if(!event.target.reportValidity())return;const message=host.querySelector('#auth-message');message.textContent='Signing in…';const fd=new FormData(event.target);try{const data=await auth('POST',{email:String(fd.get('email')||''),password:String(fd.get('password')||'')});applySession(data.session);location.hash=data.session?.role==='platform_admin'?'platform':'analyst';route();}catch(err){message.textContent=err.message||'Sign-in failed.';}});
  document.addEventListener('click',async event=>{const logout=event.target.closest('[data-auth-logout]');if(logout){event.preventDefault();logout.disabled=true;try{await auth('DELETE');}catch{}applySession(null);location.hash='login';route();return;}if(event.target.closest('[data-client-users]')){event.preventDefault();await showUsers();return;}if(event.target.closest('[data-user-close]')){userManagerShell().close();return;}const action=event.target.closest('[data-user-action]');if(action){event.preventDefault();try{await updateUser(action.dataset.userAction,action.dataset.userId);}catch(err){alert(err.message);}return;}});
  document.addEventListener('submit',async event=>{if(event.target.id!=='invite-user-form')return;event.preventDefault();const fd=new FormData(event.target);try{await userApi('POST',{action:'invite',name:String(fd.get('name')||''),email:String(fd.get('email')||'')});await showUsers();}catch(err){alert(err.message);}});
  document.addEventListener('submit',event=>{if(event.target.id!=='profile-form')return;event.preventDefault();const fd=new FormData(event.target);const name=String(fd.get('name')||'').trim();if(!name)return;try{localStorage.setItem('ontotrail_profile_name',name);}catch{}if(session){session={...session,name};applySession(session);}event.target.querySelector('button[type="submit"]').textContent='Saved';setTimeout(()=>{const b=event.target.querySelector('button[type="submit"]');if(b)b.textContent='Save name';},1200);});
  document.addEventListener('click',event=>{if(event.target.closest('[data-profile-password]')){event.preventDefault();alert('Password changes are managed by the workspace administrator in this hackathon environment.');}});
  window.addEventListener('hashchange',route);refreshSession();
}
