-- OntoTrail / Nova Mobility India synthetic internal operations layer
-- Purpose: model a fictional enterprise client's ERP / supplier / PO / shipment / inventory data
-- and enrich it with real Snowflake Marketplace TradePrism + Pelmorex intelligence.
--
-- IMPORTANT DATA BOUNDARY
-- * NOVA_* operational tables below are SYNTHETIC hackathon data.
-- * INDIA_TRADE_RISK_ENRICHED remains derived from real Marketplace sources.
-- * Do not present Nova rows as real company records.
--
-- Run after the Marketplace setup that creates:
--   ONTOTRAIL.SUPPLY_CHAIN.INDIA_TRADE_RISK_ENRICHED

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ONTOTRAIL_WH;
USE DATABASE ONTOTRAIL;
USE SCHEMA SUPPLY_CHAIN;

CREATE OR REPLACE TABLE NOVA_SUPPLIER_MASTER (
    SUPPLIER_ID VARCHAR,
    SUPPLIER_NAME VARCHAR,
    ORIGIN_ISO VARCHAR,
    ORIGIN_COUNTRY VARCHAR,
    SUPPLIER_TIER VARCHAR,
    CATEGORY VARCHAR,
    PRIMARY_HS4 VARCHAR,
    CRITICALITY VARCHAR,
    PAYMENT_TERMS VARCHAR,
    STATUS VARCHAR
);

INSERT INTO NOVA_SUPPLIER_MASTER VALUES
('SUP-NV-001','Shenzhen E-Power Systems','CHN','China','Tier 1','Battery systems','8507','HIGH','NET 45','ACTIVE'),
('SUP-NV-002','RheinMotion Controls GmbH','DEU','Germany','Tier 1','Power electronics','8504','HIGH','NET 45','ACTIVE'),
('SUP-NV-003','Aichi Drive Technologies','JPN','Japan','Tier 1','Electric drive','8501','HIGH','NET 60','ACTIVE'),
('SUP-NV-004','Hanul Semiconductor Co.','KOR','South Korea','Tier 2','Semiconductors','8542','HIGH','NET 45','ACTIVE'),
('SUP-NV-005','Michigan Sensor Systems','USA','United States','Tier 2','Sensors','9031','MEDIUM','NET 30','ACTIVE'),
('SUP-NV-006','Britannia HV Connectors','GBR','United Kingdom','Tier 2','Electrical connectors','8536','MEDIUM','NET 45','ACTIVE'),
('SUP-NV-007','Siam Thermal Solutions','THA','Thailand','Tier 2','Thermal systems','8419','MEDIUM','NET 45','ACTIVE'),
('SUP-NV-008','VietFlow Pumps JSC','VNM','Vietnam','Tier 2','Cooling pumps','8413','MEDIUM','NET 30','ACTIVE');

CREATE OR REPLACE TABLE NOVA_MATERIAL_MASTER (
    MATERIAL_ID VARCHAR,
    MATERIAL_NAME VARCHAR,
    HS4_CODE VARCHAR,
    COMMODITY_GROUP VARCHAR,
    UOM VARCHAR,
    UNIT_COST_USD NUMBER(18,2),
    CRITICALITY VARCHAR,
    PRIMARY_PLANT VARCHAR
);

INSERT INTO NOVA_MATERIAL_MASTER VALUES
('MAT-BAT-001','LFP battery module','8507','Battery systems','EA',4850,'HIGH','Bengaluru EV Plant'),
('MAT-INV-001','Traction inverter','8504','Power electronics','EA',1240,'HIGH','Bengaluru EV Plant'),
('MAT-MOT-001','Permanent magnet traction motor','8501','Electric drive','EA',2180,'HIGH','Pune Powertrain Plant'),
('MAT-CHP-001','Automotive power semiconductor set','8542','Semiconductors','SET',620,'HIGH','Bengaluru EV Plant'),
('MAT-SNS-001','Vehicle sensor module','9031','Sensors','EA',185,'MEDIUM','Chennai Electronics Plant'),
('MAT-CON-001','High-voltage connector set','8536','Electrical connectors','SET',92,'MEDIUM','Bengaluru EV Plant'),
('MAT-THM-001','Battery thermal control unit','8419','Thermal systems','EA',410,'MEDIUM','Pune Powertrain Plant'),
('MAT-PMP-001','Electric coolant pump','8413','Cooling pumps','EA',138,'MEDIUM','Pune Powertrain Plant');

CREATE OR REPLACE TABLE NOVA_PURCHASE_ORDERS (
    PO_ID VARCHAR,
    PO_DATE DATE,
    SUPPLIER_ID VARCHAR,
    MATERIAL_ID VARCHAR,
    PLANT_NAME VARCHAR,
    ORDER_QTY NUMBER,
    RECEIVED_QTY NUMBER,
    UNIT_COST_USD NUMBER(18,2),
    PO_VALUE_USD NUMBER(18,2),
    PROMISED_DATE DATE,
    STATUS VARCHAR
);

INSERT INTO NOVA_PURCHASE_ORDERS
WITH generated_po_rows AS (
    SELECT
      SEQ4()+1 N
    FROM TABLE(GENERATOR(ROWCOUNT=>32))
),
base AS (
    SELECT
      N,
      CASE MOD(N-1,8)
        WHEN 0 THEN 'SUP-NV-001' WHEN 1 THEN 'SUP-NV-002'
        WHEN 2 THEN 'SUP-NV-003' WHEN 3 THEN 'SUP-NV-004'
        WHEN 4 THEN 'SUP-NV-005' WHEN 5 THEN 'SUP-NV-006'
        WHEN 6 THEN 'SUP-NV-007' ELSE 'SUP-NV-008' END SUPPLIER_ID,
      CASE MOD(N-1,8)
        WHEN 0 THEN 'MAT-BAT-001' WHEN 1 THEN 'MAT-INV-001'
        WHEN 2 THEN 'MAT-MOT-001' WHEN 3 THEN 'MAT-CHP-001'
        WHEN 4 THEN 'MAT-SNS-001' WHEN 5 THEN 'MAT-CON-001'
        WHEN 6 THEN 'MAT-THM-001' ELSE 'MAT-PMP-001' END MATERIAL_ID,
      40 + MOD(N*31,260) ORDER_QTY
    FROM generated_po_rows
)
SELECT
  'PO-NV-'||LPAD(N::VARCHAR,4,'0'),
  DATEADD('day',-MOD(N*3,70),'2026-09-22'::DATE),
  b.SUPPLIER_ID,
  b.MATERIAL_ID,
  m.PRIMARY_PLANT,
  ORDER_QTY,
  CASE
    WHEN MOD(N,7)=0 THEN FLOOR(ORDER_QTY*0.35)
    WHEN MOD(N,5)=0 THEN FLOOR(ORDER_QTY*0.70)
    ELSE ORDER_QTY
  END,
  m.UNIT_COST_USD,
  ROUND(ORDER_QTY*m.UNIT_COST_USD,2),
  DATEADD('day',7+MOD(N*5,38),'2026-09-22'::DATE),
  CASE
    WHEN MOD(N,7)=0 THEN 'DELAYED'
    WHEN MOD(N,5)=0 THEN 'PARTIALLY_RECEIVED'
    WHEN MOD(N,3)=0 THEN 'IN_TRANSIT'
    ELSE 'OPEN'
  END
FROM base b
JOIN NOVA_MATERIAL_MASTER m USING (MATERIAL_ID);

CREATE OR REPLACE TABLE NOVA_SHIPMENTS (
    SHIPMENT_ID VARCHAR,
    PO_ID VARCHAR,
    SUPPLIER_ID VARCHAR,
    MATERIAL_ID VARCHAR,
    ORIGIN_ISO VARCHAR,
    TRANSPORT_MODE VARCHAR,
    SHIPPED_QTY NUMBER,
    DEPARTURE_DATE DATE,
    ETA_DATE DATE,
    SHIPMENT_STATUS VARCHAR
);

INSERT INTO NOVA_SHIPMENTS
SELECT
  'SHP-NV-'||LPAD(ROW_NUMBER() OVER(ORDER BY p.PO_ID)::VARCHAR,4,'0'),
  p.PO_ID,
  p.SUPPLIER_ID,
  p.MATERIAL_ID,
  s.ORIGIN_ISO,
  CASE
    WHEN s.ORIGIN_ISO IN ('CHN','JPN','KOR','THA','VNM') THEN 'SEA'
    WHEN s.ORIGIN_ISO IN ('DEU','GBR') AND MOD(ROW_NUMBER() OVER(ORDER BY p.PO_ID),3)=0 THEN 'AIR'
    WHEN s.ORIGIN_ISO='USA' THEN 'AIR'
    ELSE 'SEA'
  END,
  GREATEST(p.ORDER_QTY-p.RECEIVED_QTY,CEIL(p.ORDER_QTY*0.25)),
  DATEADD('day',-MOD(ROW_NUMBER() OVER(ORDER BY p.PO_ID)*2,16),'2026-09-22'::DATE),
  p.PROMISED_DATE,
  CASE
    WHEN p.STATUS='DELAYED' THEN 'DELAYED'
    WHEN p.STATUS='PARTIALLY_RECEIVED' THEN 'IN_TRANSIT'
    ELSE 'BOOKED'
  END
FROM NOVA_PURCHASE_ORDERS p
JOIN NOVA_SUPPLIER_MASTER s USING (SUPPLIER_ID)
WHERE p.STATUS IN ('DELAYED','PARTIALLY_RECEIVED','IN_TRANSIT','OPEN');

CREATE OR REPLACE TABLE NOVA_INVENTORY (
    MATERIAL_ID VARCHAR,
    PLANT_NAME VARCHAR,
    ON_HAND_QTY NUMBER,
    SAFETY_STOCK_QTY NUMBER,
    DAILY_DEMAND_QTY NUMBER,
    DAYS_OF_COVER NUMBER(12,1),
    SNAPSHOT_DATE DATE
);

INSERT INTO NOVA_INVENTORY
SELECT
  MATERIAL_ID,
  PRIMARY_PLANT,
  CASE MATERIAL_ID
    WHEN 'MAT-BAT-001' THEN 185
    WHEN 'MAT-INV-001' THEN 310
    WHEN 'MAT-MOT-001' THEN 142
    WHEN 'MAT-CHP-001' THEN 420
    WHEN 'MAT-SNS-001' THEN 860
    WHEN 'MAT-CON-001' THEN 1120
    WHEN 'MAT-THM-001' THEN 265
    ELSE 340 END,
  CASE WHEN CRITICALITY='HIGH' THEN 120 ELSE 180 END,
  CASE MATERIAL_ID
    WHEN 'MAT-BAT-001' THEN 28
    WHEN 'MAT-INV-001' THEN 34
    WHEN 'MAT-MOT-001' THEN 22
    WHEN 'MAT-CHP-001' THEN 48
    WHEN 'MAT-SNS-001' THEN 72
    WHEN 'MAT-CON-001' THEN 95
    WHEN 'MAT-THM-001' THEN 26
    ELSE 31 END,
  ROUND(ON_HAND_QTY/NULLIF(DAILY_DEMAND_QTY,0),1),
  '2026-09-22'::DATE
FROM (
  SELECT
    MATERIAL_ID, PRIMARY_PLANT, CRITICALITY,
    CASE MATERIAL_ID
      WHEN 'MAT-BAT-001' THEN 185
      WHEN 'MAT-INV-001' THEN 310
      WHEN 'MAT-MOT-001' THEN 142
      WHEN 'MAT-CHP-001' THEN 420
      WHEN 'MAT-SNS-001' THEN 860
      WHEN 'MAT-CON-001' THEN 1120
      WHEN 'MAT-THM-001' THEN 265
      ELSE 340 END ON_HAND_QTY,
    CASE MATERIAL_ID
      WHEN 'MAT-BAT-001' THEN 28
      WHEN 'MAT-INV-001' THEN 34
      WHEN 'MAT-MOT-001' THEN 22
      WHEN 'MAT-CHP-001' THEN 48
      WHEN 'MAT-SNS-001' THEN 72
      WHEN 'MAT-CON-001' THEN 95
      WHEN 'MAT-THM-001' THEN 26
      ELSE 31 END DAILY_DEMAND_QTY
  FROM NOVA_MATERIAL_MASTER
);

CREATE OR REPLACE VIEW NOVA_MOBILITY_OPERATIONS AS
SELECT
  p.PO_ID,
  p.PO_DATE,
  p.PROMISED_DATE,
  p.STATUS PO_STATUS,
  p.ORDER_QTY,
  p.RECEIVED_QTY,
  p.PO_VALUE_USD,
  s.SUPPLIER_ID,
  s.SUPPLIER_NAME,
  s.ORIGIN_ISO,
  s.ORIGIN_COUNTRY,
  s.SUPPLIER_TIER,
  s.CATEGORY,
  s.CRITICALITY SUPPLIER_CRITICALITY,
  m.MATERIAL_ID,
  m.MATERIAL_NAME,
  m.HS4_CODE,
  m.COMMODITY_GROUP,
  m.CRITICALITY MATERIAL_CRITICALITY,
  p.PLANT_NAME,
  sh.SHIPMENT_ID,
  sh.TRANSPORT_MODE,
  sh.ETA_DATE,
  sh.SHIPMENT_STATUS,
  inv.ON_HAND_QTY,
  inv.SAFETY_STOCK_QTY,
  inv.DAILY_DEMAND_QTY,
  inv.DAYS_OF_COVER,
  inv.SNAPSHOT_DATE
FROM NOVA_PURCHASE_ORDERS p
JOIN NOVA_SUPPLIER_MASTER s USING (SUPPLIER_ID)
JOIN NOVA_MATERIAL_MASTER m USING (MATERIAL_ID)
LEFT JOIN NOVA_SHIPMENTS sh USING (PO_ID,SUPPLIER_ID,MATERIAL_ID)
LEFT JOIN NOVA_INVENTORY inv USING (MATERIAL_ID,PLANT_NAME);

CREATE OR REPLACE VIEW NOVA_MOBILITY_RISK_ENRICHED AS
WITH ext AS (
  SELECT
    ORIGIN_ISO,
    HS4_STR,
    MAX(ORIGIN_COUNTRY) MARKETPLACE_ORIGIN_COUNTRY,
    SUM(NOMINAL_TRADE_VALUE) INDIA_IMPORT_VALUE_USD,
    SUM(NOMINAL_BY_SEA)/NULLIF(SUM(NOMINAL_TRADE_VALUE),0)*100 MARKET_SEA_DEPENDENCY_PCT,
    SUM(NOMINAL_BY_AIR)/NULLIF(SUM(NOMINAL_TRADE_VALUE),0)*100 MARKET_AIR_DEPENDENCY_PCT,
    MAX(IFF(WEATHER_DATA_AVAILABLE,1,0)) WEATHER_DATA_AVAILABLE,
    MAX(WEATHER_RISK_SCORE) WEATHER_RISK_SCORE,
    MAX(WEATHER_RISK_LEVEL) WEATHER_RISK_LEVEL,
    MAX(AFFECTED_LOCATION_PCT) AFFECTED_LOCATION_PCT
  FROM INDIA_TRADE_RISK_ENRICHED
  WHERE TRADE_YEAR=2026
    AND TRADE_DIRECTION='IMPORT'
  GROUP BY ORIGIN_ISO,HS4_STR
)
SELECT
  o.*,
  ext.INDIA_IMPORT_VALUE_USD,
  ext.MARKET_SEA_DEPENDENCY_PCT,
  ext.MARKET_AIR_DEPENDENCY_PCT,
  IFF(ext.WEATHER_DATA_AVAILABLE=1,TRUE,FALSE) WEATHER_DATA_AVAILABLE,
  ext.WEATHER_RISK_SCORE,
  ext.WEATHER_RISK_LEVEL,
  ext.AFFECTED_LOCATION_PCT,
  IFF(ext.ORIGIN_ISO IS NULL,FALSE,TRUE) MARKETPLACE_MATCH_AVAILABLE,
  CASE
    WHEN o.DAYS_OF_COVER < 7 THEN 'HIGH'
    WHEN o.DAYS_OF_COVER < 14 THEN 'MEDIUM'
    ELSE 'LOW'
  END INVENTORY_RISK_LEVEL,
  CASE
    WHEN o.PO_STATUS='DELAYED' AND o.DAYS_OF_COVER < 7 THEN 'HIGH'
    WHEN o.PO_STATUS IN ('DELAYED','PARTIALLY_RECEIVED') OR o.DAYS_OF_COVER < 14 THEN 'MEDIUM'
    ELSE 'LOW'
  END OPERATIONAL_RISK_LEVEL
FROM NOVA_MOBILITY_OPERATIONS o
LEFT JOIN ext
  ON ext.ORIGIN_ISO=o.ORIGIN_ISO
 AND LPAD(ext.HS4_STR::VARCHAR,4,'0')=LPAD(o.HS4_CODE::VARCHAR,4,'0');

CREATE ROLE IF NOT EXISTS ONTOTRAIL_APP_ROLE;
GRANT SELECT ON TABLE NOVA_SUPPLIER_MASTER TO ROLE ONTOTRAIL_APP_ROLE;
GRANT SELECT ON TABLE NOVA_MATERIAL_MASTER TO ROLE ONTOTRAIL_APP_ROLE;
GRANT SELECT ON TABLE NOVA_PURCHASE_ORDERS TO ROLE ONTOTRAIL_APP_ROLE;
GRANT SELECT ON TABLE NOVA_SHIPMENTS TO ROLE ONTOTRAIL_APP_ROLE;
GRANT SELECT ON TABLE NOVA_INVENTORY TO ROLE ONTOTRAIL_APP_ROLE;
GRANT SELECT ON VIEW NOVA_MOBILITY_OPERATIONS TO ROLE ONTOTRAIL_APP_ROLE;
GRANT SELECT ON VIEW NOVA_MOBILITY_RISK_ENRICHED TO ROLE ONTOTRAIL_APP_ROLE;

-- Validation
SELECT COUNT(*) SUPPLIERS FROM NOVA_SUPPLIER_MASTER;
SELECT COUNT(*) MATERIALS FROM NOVA_MATERIAL_MASTER;
SELECT COUNT(*) PURCHASE_ORDERS FROM NOVA_PURCHASE_ORDERS;
SELECT COUNT(*) SHIPMENTS FROM NOVA_SHIPMENTS;
SELECT COUNT(*) INVENTORY_ROWS FROM NOVA_INVENTORY;

SELECT
  SUM(PO_VALUE_USD) OPEN_PO_VALUE_USD,
  COUNT(DISTINCT SUPPLIER_ID) SUPPLIERS,
  COUNT_IF(PO_STATUS='DELAYED') DELAYED_POS,
  COUNT_IF(DAYS_OF_COVER < 7) LOW_COVER_POS,
  SUM(IFF(WEATHER_RISK_LEVEL IN ('MEDIUM','HIGH'),PO_VALUE_USD,0)) WEATHER_LINKED_PO_VALUE_USD
FROM NOVA_MOBILITY_RISK_ENRICHED;

SELECT
  SUPPLIER_NAME,
  ORIGIN_COUNTRY,
  CATEGORY,
  SUM(PO_VALUE_USD) PO_VALUE_USD,
  MIN(DAYS_OF_COVER) MIN_DAYS_OF_COVER,
  MAX(WEATHER_RISK_LEVEL) WEATHER_RISK_LEVEL,
  MAX(MARKET_SEA_DEPENDENCY_PCT) MARKET_SEA_DEPENDENCY_PCT
FROM NOVA_MOBILITY_RISK_ENRICHED
GROUP BY SUPPLIER_NAME,ORIGIN_COUNTRY,CATEGORY
ORDER BY PO_VALUE_USD DESC;
